=== izerui/validator/src/main/resources/dtd/validation.dtd
<!-- 表单验证 -->
<!ELEMENT validation (formset?)>


<!-- 多个验证form集合 -->
<!ELEMENT formset (form*)>

<!--
    验证表单,可自定义,比如区分行业,区分账套,区分类型等根据不同的名称加载不同的验证方案
-->
<!ELEMENT form (field*)>
<!-- 属性名,用来区分验证表单,不可以包含特殊字符 -->
<!ATTLIST form name CDATA #REQUIRED>
<!-- 说明 -->
<!ATTLIST form description CDATA #IMPLIED>
<!-- 继承自其他form, 多个以逗号区分-->
<!--<!ATTLIST form extends CDATA #IMPLIED>-->

<!-- 要验证的字段 -->
<!ELEMENT field (validator*)>
<!-- 字段名 -->
<!ATTLIST field name CDATA #REQUIRED>

<!-- 选择一种验证器执行验证 -->
<!ELEMENT validator (#PCDATA)>
<!-- 执行的validator的名称 -->
<!ATTLIST validator name CDATA #REQUIRED>
<!-- 验证失败的错误信息 -->
<!ATTLIST validator msg CDATA #REQUIRED>
<!-- 传入的参数 -->
<!ATTLIST validator var CDATA #IMPLIED>

=== izerui/validator/src/main/resources/demos/validation.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE validation PUBLIC
        "-//ecworking//DTD Form Validator Rules Configuration 1.0.0//EN"
        "https://raw.githubusercontent.com/izerui/dtd/master/validation.dtd">
<validation>
    <formset>
        <form name="ent_type_1" description="跟单管理-贸易版验证">
            <field name="name">
                <validator name="not_null" msg="名称不能为空"/>
                <!--<validator name="lyh" msg="不是刘玉华"/>-->
            </field>
            <field name="email">
                <validator name="not_null" msg="邮件不能为空"/>
                <validator name="email" msg="邮件格式不正确"/>
            </field>
            <field name="dateFormat">
                <validator name="date_pattern" var="yyyy-MM-dd" msg="格式不对"/>
            </field>
        </form>

        <form name="ent_type_2" description="跟单管理-制造版验证">
            <field name="field01">
                <validator name="null" msg="必须为空"/>
            </field>
        </form>
    </formset>
</validation>
